### ISSUE TITLE
Failed user signup

### ISSUE THREAD

**Issue by itspasindu** [adrianhajdin/storage_management_solution#5]
AppwriteException: Invalid document structure: Missing required attribute "accountid"
    at e.call (F:\storage_manager\storage_manage\.next\server\chunks\479.js:80:86686)
    at async m.createDocument (F:\storage_manager\storage_manage\.next\server\chunks\479.js:80:122679)
    at async x (F:\storage_manager\storage_manage\.next\server\chunks\597.js:1:1948)
    at async (F:\storage_manager\storage_manage\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:127:1299)
    at async rd (F:\storage_manager\storage_manage\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:126:11787)
    at async n7 (F:\storage_manager\storage_manage\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:132:1237)
    at async doRender (F:\storage_manager\storage_manage\node_modules\next\dist\server\base-server.js:1587:34)
    at async responseGenerator (F:\storage_manager\storage_manage\node_modules\next\dist\server\base-server.js:1834:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (F:\storage_manager\storage_manage\node_modules\next\dist\server\base-server.js:1876:28) {
  code: 400,
  type: 'document_invalid_structure',
  response: [Object],
  digest: '3021347741'

**Comment by AnasSiddiqui18** [comment]
@itspasindu You need to add ur appwrite account credentials before performing authentication in the application. Please read the readMe guide, and follow it along.

**Comment by itspasindu** [comment]
> @itspasindu You need to add ur appwrite account credentials before performing authentication in the application. Please read the readMe guide, and follow it along.

i tried but not fixed my issue

**Comment by YxngDjin** [comment]
dont now why but on my side the solution was to delete and make a new Appwrite Project

**Comment by TusharGupta0202** [comment]
Check If you are doing a issue with capital I or small i
