### ISSUE TITLE
User not able to redirect to / after login/signup

### ISSUE THREAD

**Issue by ArhanAnsari** [adrianhajdin/storage_management_solution#6]
Hey there,
Seeing when trying to signin/signup, even though I signin/signup as new user and first time and is excepting me to have some files uploaded.

Error: No session
    at o (/var/task/.next/server/chunks/501.js:1:45028)
    at async x (/var/task/.next/server/chunks/501.js:1:43422)
    at async u (/var/task/.next/server/chunks/501.js:1:33022)
Error: No session
    at o (/var/task/.next/server/chunks/501.js:1:45028)
    at async b (/var/task/.next/server/chunks/501.js:1:41159)
    at async h (/var/task/.next/server/app/(root)/page.js:5:38903) Error calculating total space used:,
Error: No session
    at o (/var/task/.next/server/chunks/501.js:1:45028)
    at async x (/var/task/.next/server/chunks/501.js:1:43422)
    at async h (/var/task/.next/server/chunks/501.js:1:40118)
    at async h (/var/task/.next/server/app/(root)/page.js:5:38903)
Error: User not found
    at h (/var/task/.next/server/chunks/501.js:1:40147) Failed to get files
⨯ Error: No session
    at o (/var/task/.next/server/chunks/501.js:1:45028)
    at async b (/var/task/.next/server/chunks/501.js:1:41159)
    at async h (/var/task/.next/server/app/(root)/page.js:5:38903) {
  digest: '2077185219'
}

**Comment by ArhanAnsari** [comment]
Also I am seeing this at / (https://storeit-five.vercel.app/)

**Comment by ArhanAnsari** [comment]
@developingfaizaan @AnasSiddiqui18 Could you please help me?

**Comment by AnasSiddiqui18** [comment]
> @developingfaizaan @AnasSiddiqui18 Could you please help me?

Hello 👋, Hope you're fine and doing great. It's an expected behavior where the user will get redirect to the sign-in route if it's not authenticated, first login and then you'll be redirect to the ```/``` route.

**Comment by ArhanAnsari** [comment]
> > @developingfaizaan @AnasSiddiqui18 Could you please help me?
> 
> Hello 👋, Hope you're fine and doing great. It's an expected behavior where the user will get redirect to the sign-in route if it's not authenticated, first login and then you'll be redirect to the `/` route.

After login I am seeing the error and share the error log (as given above)

**Comment by ArhanAnsari** [comment]
> > > @developingfaizaan @AnasSiddiqui18 Could you please help me?
> > 
> > 
> > Hello 👋, Hope you're fine and doing great. It's an expected behavior where the user will get redirect to the sign-in route if it's not authenticated, first login and then you'll be redirect to the `/` route.
> 
> After login I am seeing the error and share the error log (as given above)

On / even after login in and everything is fine with appwrite and storing the user data into appwrite, but still don't know why it is causing this error even though I signup for first time and have no files there. (Directly, after configuration of .env and directly on vercel production url)

**Comment by ArhanAnsari** [comment]
@AnasSiddiqui18 
Heres my error message and log from the developmental server
> store_it@0.1.0 dev
> next dev --turbopack

   ▲ Next.js 15.0.2 (Turbopack)
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Starting...
Slow filesystem detected. If E:\My Projects\VS Code Projects\Website\storage_management_solution\.next is a network drive, consider moving it to a local folder. If you have an antivirus enabled, consider excluding your project directory.
 ✓ Ready in 30.8s
 ○ Compiling / ...
 ✓ Compiled / in 234.2s

Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getCurrentUser (turbopack://[project]/lib/actions/user.actions.ts:98:35)
    at async Layout (turbopack://[project]/app/(root)/layout.tsx:12:22)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 |
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getTotalSpaceUsed (turbopack://[project]/lib/actions/file.actions.ts:199:26)
    at async Dashboard (turbopack://[project]/app/(root)/page.tsx:15:30)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 | Error calculating total space used:,
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getCurrentUser (turbopack://[project]/lib/actions/user.actions.ts:98:35)
    at async getFiles (turbopack://[project]/lib/actions/file.actions.ts:102:24)
    at async Dashboard (turbopack://[project]/app/(root)/page.tsx:15:30)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 |
Error: User not found
    at getFiles (turbopack://[project]/lib/actions/file.actions.ts:104:28)
  102 |     const currentUser = await getCurrentUser();
  103 |
> 104 |     if (!currentUser) throw new Error("User not found");
      |                            ^
  105 |
  106 |     const queries = createQueries(currentUser, types, searchText, sort, limit);
  107 | Failed to get files
 ⨯ Error: No session
    at createSessionClient (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__d3aee0._.js:758:43)
    at async getTotalSpaceUsed (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__a3938f._.js:329:31)       
    at async Promise.all (index 1)
    at async Dashboard (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__a3938f._.js:420:33)
digest: "1616161541"

GET / 307 in 237903ms
 ○ Compiling /sign-in ...
 ✓ Compiled /sign-in in 15s
 GET /sign-in 200 in 16968ms
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 5.4s
 GET /favicon.ico?favicon.27767dc4.ico 200 in 5920ms
 POST /sign-in 200 in 993ms
 POST /sign-in 200 in 984ms
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getCurrentUser (turbopack://[project]/lib/actions/user.actions.ts:98:35)
    at async Layout (turbopack://[project]/app/(root)/layout.tsx:12:22)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 |
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getTotalSpaceUsed (turbopack://[project]/lib/actions/file.actions.ts:199:26)
    at async Dashboard (turbopack://[project]/app/(root)/page.tsx:15:30)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 | Error calculating total space used:,
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getCurrentUser (turbopack://[project]/lib/actions/user.actions.ts:98:35)
    at async getFiles (turbopack://[project]/lib/actions/file.actions.ts:102:24)
    at async Dashboard (turbopack://[project]/app/(root)/page.tsx:15:30)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 |
Error: User not found
    at getFiles (turbopack://[project]/lib/actions/file.actions.ts:104:28)
  102 |     const currentUser = await getCurrentUser();
  103 |
> 104 |     if (!currentUser) throw new Error("User not found");
      |                            ^
  105 |
  106 |     const queries = createQueries(currentUser, types, searchText, sort, limit);
  107 | Failed to get files
 GET / 200 in 605ms
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getCurrentUser (turbopack://[project]/lib/actions/user.actions.ts:98:35)
    at async Layout (turbopack://[project]/app/(root)/layout.tsx:12:22)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 |
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getTotalSpaceUsed (turbopack://[project]/lib/actions/file.actions.ts:199:26)
    at async Dashboard (turbopack://[project]/app/(root)/page.tsx:15:30)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 | Error calculating total space used:,
Error: No session
    at createSessionClient (turbopack://[project]/lib/appwrite/index.ts:14:40)
    at async getCurrentUser (turbopack://[project]/lib/actions/user.actions.ts:98:35)
    at async getFiles (turbopack://[project]/lib/actions/file.actions.ts:102:24)
    at async Dashboard (turbopack://[project]/app/(root)/page.tsx:15:30)
  12 |   const session = (await cookies()).get("appwrite-session");
  13 |
> 14 |   if (!session || !session.value) throw new Error("No session");
     |                                        ^
  15 |
  16 |   client.setSession(session.value);
  17 |
Error: User not found
    at getFiles (turbopack://[project]/lib/actions/file.actions.ts:104:28)
  102 |     const currentUser = await getCurrentUser();
  103 |
> 104 |     if (!currentUser) throw new Error("User not found");
      |                            ^
  105 |
  106 |     const queries = createQueries(currentUser, types, searchText, sort, limit);
  107 | Failed to get files
 GET / 200 in 490ms
 GET /sign-in 200 in 234ms
 ⨯ Error: No session
    at createSessionClient (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__d3aee0._.js:758:43)
    at async getTotalSpaceUsed (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__a3938f._.js:329:31)       
    at async Promise.all (index 1)
    at async Dashboard (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__a3938f._.js:420:33)
digest: "1616161541"
 ⨯ Error: No session
    at createSessionClient (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__d3aee0._.js:758:43)
    at async getTotalSpaceUsed (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__a3938f._.js:329:31)       
    at async Promise.all (index 1)
    at async Dashboard (E:\My Projects\VS Code Projects\Website\storage_management_solution\.next\server\chunks\ssr\[root of the server]__a3938f._.js:420:33)
digest: "1616161541"
 GET /sign-in 200 in 210ms

**Comment by ArhanAnsari** [comment]
@AnasSiddiqui18 @developingfaizaan @adrianhajdin

This issue is SOLVED

**Comment by odinson-codes** [comment]
How did you solve it can you share. I am facing same issue.

**Comment by ArhanAnsari** [comment]
> How did you solve it can you share. I am facing same issue.

By adding NEXT_APPWRITE_SECRET

**Comment by Kairat-Nobels** [comment]
> > How did you solve it can you share. I am facing same issue.
> 
> By adding NEXT_APPWRITE_SECRET

can you tell me more information about your fixing this issue
I cant fix this same issue, I add next apwrite secret and appwrite secret key

but the result is the same

**Comment by ArhanAnsari** [comment]
> > > How did you solve it can you share. I am facing same issue.
> > 
> > 
> > By adding NEXT_APPWRITE_SECRET
> 
> can you tell me more information about your fixing this issue I cant fix this same issue, I add next apwrite secret and appwrite secret key
> 
> but the result is the same

See my code, I forgot about it

**Comment by odinson-codes** [comment]
> > > How did you solve it can you share. I am facing same issue.
> > 
> > 
> > By adding NEXT_APPWRITE_SECRET
> 
> can you tell me more information about your fixing this issue I cant fix this same issue, I add next apwrite secret and appwrite secret key
> 
> but the result is the same

I was able to solve the problem by creating another appwrite project and using a new credentials

**Comment by moment0517** [comment]
> > > How did you solve it can you share. I am facing same issue.
> > 
> > 
> > By adding NEXT_APPWRITE_SECRET
> 
> can you tell me more information about your fixing this issue I cant fix this same issue, I add next apwrite secret and appwrite secret key
> 
> but the result is the same

check the .env.local file， NEXT_APPWRITE_KEY not NEXT_APPWRITE_SECRET

**Comment by ArhanAnsari** [comment]
> > > > How did you solve it can you share. I am facing same issue.
> > > 
> > > 
> > > By adding NEXT_APPWRITE_SECRET
> > 
> > 
> > can you tell me more information about your fixing this issue I cant fix this same issue, I add next apwrite secret and appwrite secret key
> > but the result is the same
> 
> check the .env.local file， NEXT_APPWRITE_KEY not NEXT_APPWRITE_SECRET

Sorry, my bad, I just checked that it is NEXT_APPWRITE_KEY not NEXT_APPWRITE_SECRET. I actually forgot, just checked my vercel deployment.

![Image](https://github.com/user-attachments/assets/d9b0668a-f6ef-4e1d-a6d3-d0fe38d42a68)
